project_id = "eyxqdgosabtgizwsrsiq"

[functions.fetch-livecoinwatch-prices]
verify_jwt = false

[functions.fetch-bybit-candles]
verify_jwt = false

[functions.fetch-coinmarketcap-data]
verify_jwt = false

[functions.calculate-technical-indicators]
verify_jwt = false

[functions.chat-ai]
verify_jwt = true

[functions.initialize-market-data]
verify_jwt = false

[functions.update-market-data]
verify_jwt = false
